"""HTML executive report builder — generates downloadable analysis reports."""

from typing import Dict, Any, Optional, List
from pathlib import Path
from datetime import datetime
import html

import pandas as pd

from utils.config import REPORT_OUTPUT_DIR


REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AZData — {title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }}
        .container {{ max-width: 900px; margin: 0 auto; padding: 40px 20px; }}
        h1 {{ color: #38bdf8; font-size: 2em; margin-bottom: 10px; }}
        h2 {{ color: #7dd3fc; font-size: 1.4em; margin: 30px 0 15px; border-bottom: 1px solid #1e3a5f; padding-bottom: 8px; }}
        h3 {{ color: #93c5fd; font-size: 1.1em; margin: 20px 0 10px; }}
        .meta {{ color: #94a3b8; font-size: 0.9em; margin-bottom: 30px; }}
        .card {{ background: #1e293b; border-radius: 12px; padding: 20px; margin: 15px 0; border: 1px solid #334155; }}
        .metric-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }}
        .metric {{ background: #0f172a; border-radius: 8px; padding: 15px; text-align: center; border: 1px solid #334155; }}
        .metric .value {{ font-size: 2em; font-weight: bold; color: #38bdf8; }}
        .metric .label {{ color: #94a3b8; font-size: 0.85em; margin-top: 5px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th {{ background: #334155; color: #e2e8f0; padding: 10px; text-align: left; font-size: 0.9em; }}
        td {{ padding: 8px 10px; border-bottom: 1px solid #1e3a5f; font-size: 0.85em; }}
        tr:hover {{ background: #1e3a5f; }}
        .insight {{ padding: 10px 15px; margin: 8px 0; background: #172554; border-left: 3px solid #38bdf8; border-radius: 0 6px 6px 0; }}
        .grade {{ font-size: 3em; font-weight: bold; }}
        .grade-a {{ color: #22c55e; }}
        .grade-b {{ color: #84cc16; }}
        .grade-c {{ color: #eab308; }}
        .grade-d {{ color: #f97316; }}
        .grade-f {{ color: #ef4444; }}
        .footer {{ text-align: center; color: #475569; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1e3a5f; font-size: 0.85em; }}
        .section {{ margin-bottom: 30px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AZData — Executive Analysis Report</h1>
        <div class="meta">
            Generated: {timestamp} | Dataset: {filename} | Rows: {rows:,} | Columns: {columns}
        </div>

        <div class="section">
            <h2>Data Quality</h2>
            <div class="metric-grid">
                <div class="metric">
                    <div class="value grade-{grade_class}">{quality_grade}</div>
                    <div class="label">Quality Grade</div>
                </div>
                <div class="metric">
                    <div class="value">{quality_score}</div>
                    <div class="label">Health Score (0-100)</div>
                </div>
                <div class="metric">
                    <div class="value">{total_issues}</div>
                    <div class="label">Issues Found</div>
                </div>
            </div>
            <div class="card">
                <p>{quality_summary}</p>
            </div>
        </div>

        <div class="section">
            <h2>Dataset Overview</h2>
            <div class="metric-grid">
                <div class="metric">
                    <div class="value">{numeric_count}</div>
                    <div class="label">Numeric Columns</div>
                </div>
                <div class="metric">
                    <div class="value">{categorical_count}</div>
                    <div class="label">Categorical Columns</div>
                </div>
                <div class="metric">
                    <div class="value">{datetime_count}</div>
                    <div class="label">Datetime Columns</div>
                </div>
                <div class="metric">
                    <div class="value">{missing_pct}%</div>
                    <div class="label">Missing Values</div>
                </div>
            </div>
        </div>

        <div class="section">
            <h2>AI-Generated Insights</h2>
            {insights_html}
        </div>

        <div class="section">
            <h2>Column Details</h2>
            {columns_table}
        </div>

        <div class="section">
            <h2>Numeric Statistics</h2>
            {numeric_table}
        </div>

        {anomalies_section}

        <div class="footer">
            Generated by <strong>AZData</strong> — AI-Powered Offline Data Analyst<br>
            All analysis performed locally. No data left your machine.
        </div>
    </div>
</body>
</html>"""


def build_report(
    filename: str,
    df: pd.DataFrame,
    quality_score: float = 0,
    quality_grade: str = "N/A",
    quality_summary: str = "",
    total_issues: int = 0,
    insights: List[str] = None,
    anomaly_summary: Optional[pd.DataFrame] = None,
) -> str:
    """Build an HTML executive report from analysis results.

    Args:
        filename: Original dataset filename.
        df: The analyzed DataFrame.
        quality_score: Data quality score (0-100).
        quality_grade: Letter grade (A-F).
        quality_summary: Text summary of quality.
        total_issues: Total number of quality issues.
        insights: List of insight strings.
        anomaly_summary: Optional anomaly summary DataFrame.

    Returns:
        HTML string of the report.
    """
    if insights is None:
        insights = []

    grade_class = quality_grade.lower() if quality_grade else "c"

    # Insights HTML
    insights_html = ""
    if insights:
        for insight in insights:
            safe = html.escape(str(insight))
            insights_html += f'<div class="insight">{safe}</div>\n'
    else:
        insights_html = '<div class="insight">No insights generated.</div>'

    # Columns table
    columns_table = "<table><tr><th>Column</th><th>Type</th><th>Non-Null</th><th>Unique</th><th>Null %</th></tr>"
    for col in df.columns:
        series = df[col]
        non_null = series.notna().sum()
        unique = series.nunique()
        null_pct = round(series.isna().sum() / len(df) * 100, 1) if len(df) > 0 else 0
        col_type = "numeric" if pd.api.types.is_numeric_dtype(series) else "categorical"
        columns_table += f"<tr><td>{html.escape(col)}</td><td>{col_type}</td><td>{non_null:,}</td><td>{unique:,}</td><td>{null_pct}%</td></tr>"
    columns_table += "</table>"

    # Numeric stats table
    numeric_df = df.select_dtypes(include=["number"])
    numeric_table = ""
    if len(numeric_df.columns) > 0:
        desc = numeric_df.describe().round(2)
        numeric_table = "<table><tr><th>Stat</th>"
        for col in desc.columns:
            numeric_table += f"<th>{html.escape(col)}</th>"
        numeric_table += "</tr>"
        for stat in desc.index:
            numeric_table += f"<tr><td><strong>{stat}</strong></td>"
            for col in desc.columns:
                val = desc.loc[stat, col]
                numeric_table += f"<td>{val}</td>"
            numeric_table += "</tr>"
        numeric_table += "</table>"
    else:
        numeric_table = "<p>No numeric columns found.</p>"

    # Anomalies section
    anomalies_section = ""
    if anomaly_summary is not None and len(anomaly_summary) > 0:
        anomalies_section = '<div class="section"><h2>Anomaly Detection</h2>'
        anomalies_section += "<table><tr>"
        for col_name in anomaly_summary.columns:
            anomalies_section += f"<th>{html.escape(col_name)}</th>"
        anomalies_section += "</tr>"
        for _, row in anomaly_summary.iterrows():
            anomalies_section += "<tr>"
            for val in row:
                anomalies_section += f"<td>{html.escape(str(val))}</td>"
            anomalies_section += "</tr>"
        anomalies_section += "</table></div>"

    # Fill template
    report_html = REPORT_TEMPLATE.format(
        title=html.escape(filename),
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        filename=html.escape(filename),
        rows=len(df),
        columns=len(df.columns),
        grade_class=grade_class,
        quality_grade=quality_grade,
        quality_score=round(quality_score, 1),
        total_issues=total_issues,
        quality_summary=html.escape(quality_summary),
        numeric_count=len(numeric_df.columns),
        categorical_count=len(df.select_dtypes(include=["object", "category"]).columns),
        datetime_count=len(df.select_dtypes(include=["datetime"]).columns),
        missing_pct=round(df.isna().sum().sum() / (df.shape[0] * df.shape[1]) * 100, 1) if df.shape[0] * df.shape[1] > 0 else 0,
        insights_html=insights_html,
        columns_table=columns_table,
        numeric_table=numeric_table,
        anomalies_section=anomalies_section,
    )

    return report_html


def save_report(
    html_content: str,
    filename: str = "report",
) -> Path:
    """Save an HTML report to disk.

    Args:
        html_content: The HTML report string.
        filename: Base filename (without extension).

    Returns:
        Path to the saved file.
    """
    REPORT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in filename)
    filepath = REPORT_OUTPUT_DIR / f"{safe_name}_{timestamp}.html"

    filepath.write_text(html_content, encoding="utf-8")
    return filepath


def save_report_pdf(
    html_content: str,
    filename: str = "report",
) -> Optional[Path]:
    """Save an HTML report as PDF via weasyprint.

    Returns None if weasyprint is not installed.
    """
    try:
        from weasyprint import HTML
    except ImportError:
        return None

    REPORT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in filename)
    filepath = REPORT_OUTPUT_DIR / f"{safe_name}_{timestamp}.pdf"

    HTML(string=html_content).write_pdf(str(filepath))
    return filepath
